module.exports = {
//App 1
None:"I didn't get you.. Can you please brief out about your question.",
Insurance: "Insurance is a contract usually between a large financial institution that offers fixed protection to another person, institution or entity against a possible future loss in return of a predetermined premium. Insurance is a Risk management tool that is taken as a precautionary measure against future risks that may or may not happen.",
CIMandate:"Under provisions of the India Motor Vehicles Act 1988 car insurance is mandatory in India. Any vehicle used for social, domestic and pleasure purpose and for the insured’s business or profession.",
CITypes:"Types of car insurance- \n • Liability only policy -This covers “Third Party Liability” for bodily injury and/ or death and property damage .Personal accident cover for owner-driver is also included. \n • Comprehensive Package Policy – This covers third party liability, damage to own car and has various features as a package. \n • Zero Depreciation Policy- This cover helps you to avail full claim without any deduction for depreciation on the value of parts replaced. Types of car insurance-• Liability only policy -This covers “Third Party Liability” for bodily injury and/ or death and property damage .Personal accident cover for owner-driver is also included.• Comprehensive Package Policy – This covers third party liability, damage to own car and has various features as a package.• Zero Depreciation Policy- This cover helps you to avail full claim without any deduction for depreciation on the value of parts replaced.Types of car insurance-• Liability only policy -This covers “Third Party Liability” for bodily injury and/ or death and property damage .Personal accident cover for owner-driver is also included.• Comprehensive Package Policy – This covers third party liability, damage to own car and has various features as a package.• Zero Depreciation Policy- This cover helps you to avail full claim without any deduction for depreciation on the value of parts replaced.",
Policy:"Policy is a stamped document which provides an evidence of the contract of the insurance between the insurer and insured.",
LiabilityPolicy:"Liability only Policy covers third party liability for bodily injury and/or death and property damage and personal Accident cover for owner-driver. It is mandatory under provisions of the India Motor Vehicles Act 1988. It can further be combined with fire and theft covers: \n • Liability Only Policy with Fire Only Cover. \n • Liability Only Policy and Theft. \n • Liability Only Policy and Fire & Theft.",
CICompPackage:"Comprehensive car insurance covers damage to own car along with third party liability. It allows safety cover against damage or loss to car against. \n • Fire, explosion, self ignition, or lightning. \n • Natural disasters like floods, hurricanes and storms, earthquakes, Landslide etc. \n • Burglary, housebreaking or theft. \n • Riot, strike or terrorist activity. \n • Accidents. \n • Malicious act. \n • Whilst in transit by road, rail, inland, waterway, lift, elevator or air.",
AddOnCover:"Add on covers, as the name suggests, are the added benefits or additional insurance covers. One can buy these on payment of an extra Premium to cover certain additional risks that might not be covered in the insurance Policy otherwise. Some of the add-on covers being offered by various insurance companies are: \n • Depreciation cover. \n • NCB protection cover. \n • Personal belongings cover. \n • Daily allowance cover. \n • Loss of keys. \n • Road assistance cover.",
Exclusion:"There are certain conditions and situations where the vehicle is not covered. The list may vary for different companies, general exclusions may be:\n • Normal depreciation, wear and tear. \n • Mechanical or electrical breakdown failure or breakages. \n • Damage to tyres and tubes unless the vehicle is also damaged.. \n • Car driven under the influence of intoxicating liquor or drugs at the time of loss.\n • Damage by person driving without a valid driving licence.\n • Damage due to war or nuclear crises. \n • Use of vehicle other than it is meant for. \n • Use of vehicle beyond specified geographical area.\n • Consequential loss. \n • Compulsory deductibles.",
Duration:"Motor insurance is issued for duration of one year and needs to be renewed every year.",
InspectVehicle:"The vehicle might need to be inspected by the insurance company representative if \n • There is a break in insurance. \n • There is a change in type of policy. \n • There is a change in policy ownership. \n • You have added accessories that you want insured. \n • If your are installing CNG/LPG kit in your vehicle, one has to get the kit endorsed in his Rc (Registration Certificate) book by the RTO (Road transport office). Additional premium is payable for the vehicle with LPG/CNG kit.",
Premium:"Premium is the financial cost of an insurance policy paid either as Lumpsum or in several installments during the period covered by the policy",
CarEval:"The Premium of vehicle insurance depends upon \n • Insured Declared Value (IDV). \n • Vehicle Make & Model. \n • Place of registration (Zone). \n • Additional covers taken. \n • Registration year of the vehicle.",
IDV:"IDV or the insured declared value of the vehicle is the value of the vehicle that it is insured for. It is fixed every year at the commencement of each policy period. It is arrived at taking into account the manufacturer’s listed selling price of the brand and model, accessories if any that are not included in the manufacturers list and annual depreciation. For vehicles aged over 5 years of age and of obsolete models the IDV is a value agreed upon between the owner and insurance company.",
PlaceOfReg:"As per The Indian Motor Tariff Act, for the purpose of vehicle insurance, India has been divided in two zones by and the Premium rates vary according to them: \n • Zone A - Ahmedabad, Bangalore, Chennai, Hyderabad, Kolkata, Mumbai, New Delhi and Pune. \n • Zone B - Rest of India.  As per The Indian Motor Tariff Act, for the purpose of vehicle insurance, India has been divided in two zones by and the Premium rates vary according to them:",
DiffCompPremium:"The difference in premium may be because of some additional covers included. Insurance companies give tariff discounts on vehicles which may vary on vehicle model, driver, and territory of use. For example an insurance company may give 30% discount and on the same vehicle for which another insurance company may be giving only 10% discount.",
Discounts:"Discounts available for the Premium of car insurance \n • Voluntary Deductible. \n • No Claim Bonus. \n • Automobile Association Membership. \n • Installing anti theft devices. \n • Discount for Vintage Cars.",
Deductible:"Deductible is the damage repair charges that the insured has to pay from his own pocket in case of the claim after which the insurance company releases the claim fund. It is the amount that is not covered under the policy. • Compulsory Deductible is the mandatory pre determined amount that the policyholder has to pay in case of accident or damages. For Private Cars (not exceeding 1500 CC) compulsory deductible is Rs. 1000 and for Private Cars (exceeding 1500 CC) it is Rs. 2000.• Voluntary Deductible is the pre determined amount that the policyholder accepts to pay on his own in case of damage or accident.  Deductible is the damage repair charges that the insured has to pay from his own pocket in case of the claim after which the insurance company releases the claim fund. It is the amount that is not covered under the policy.",
Claim:"Claim is a request for payment of the contractual benefits by the insurer that is made as soon as the contingency covered by the policy arises. A written request is made by the insured or the nominee for the insurance company to cover the incurred loss, which is submitted on a standard form provided by the insurance company.",
Greeting: "Welcome ! Please share your question."
};
