module.exports = {
None:"I didn't get you.. Can you please brief out about your question.",
WaterCome:"We supply 2.6 billion litres of drinking water to nine million people across London and the Thames Valley every day. Thirty-five per cent of the water we supply is pumped from natural underground reservoirs called aquifers. The other 65 per cent is pumped from rivers. However, the vast majority of river water is supplied from aquifers, making groundwater our most important source of water.",
WhatsinWater: "Hardness, Lead, Taste, Smell and appearance",
HardWaterCreate: "Hard water is found in areas which have a chalk and limestone geology. As water passes through the rock it picks up chalk carbonates, the concentrations of which will determine the level of hardness. All supplies in the Thames Water area are generally classified as hard. There is some variation in the degree of hardness across the area, with water in the Guildford region being the softest.",
HardWaterHarm: "There is no health risk associated with hardness.However, hard water can lead to scale forming and may also affect the appearance of hot drinks, increase soap consumption and reduce detergent efficiency. If your pipework at home contains either copper or lead pipes then the minerals in hard water can create an internal protective film. This protective film can line the pipes and prevent the metals filtering into your drinking water supply.",
HardWaterReduce: "If hardness scale becomes a problem there are a number of simple measures that can be taken to reduce the level of deposition:<br>• Reducing the temperature of your hot water to 60°C or lower to decrease the build up of scale  <br>• Place a stainless steel wire scale collector in your kettle to  reduce scale build-up. <br>• Avoid scale floating on the surface of your water by regularly rinsing your plastic kettle <br> • Follow the manufacturer’s instructions for any appliances that use water.<br>• Install a water softener. On occasions sodium levels within softened water can be higher than normal. We therefore do not recommend that softened water is used for drinking purposes. The softener should be plumbed in after the drinking water point ensure you have a separate un softened supply for drinking.",
LeadinWater: "Lead is commonly found in the environment and can  come from sources such as vehicle exhaust fumes and old paint. Lead can also be present in food, water, air and soil, and is able to build up over time in the human body which can have health implications. There are no significant levels  of lead present in the drinking water we supply as it leaves our treatment works. The network of mains, which transports the water to your tap, are not made from lead.",
ChlorineWater: "Chlorine is a disinfectant which has been used for many years in the water industry to make water safe to drink. Disinfection plays an important role in protecting public health by killing harmful bacteria. Using chlorine is better than using other disinfectants as it is effective from our treatment works right up to your tap.<br> Your water may occasionally smell or taste of chlorine after we have made a change to our water treatment processes. The level of chlorine dosed into your drinking water is carefully controlled and monitored.<br>We strive to keep the level of chlorine constant.  Unavoidable operational changes at our treatment works, or in our distributing pipes, may result in a slight taste of chlorine. Chlorine leaves our treatment works at less than one milligram per litre (one part per million), the level recommended by the World Health Organisation. By comparison, water found in swimming pools typically contains 3 milligrams per litre of chlorine which is easy to smell. <br>Treating drinking water with chlorine poses no risk to health. If you’re concerned about the taste then a good way to let the chlorine evaporate is to fill a jug with water and refrigerate it overnight.  Water kept like this should be treated as a perishable food and be consumed within 24 hours.<br> Domestic water filters or jug filters (both of which can contain activated carbon) can be used to remove chlorine from tap water. These filters should be used in accordance with the manufacturer's instructions. There is no reason to use either type of filter on health grounds, as tap water containing chlorine is perfectly safe to drink.",
ThamesWaterLook: "Every year, we carry out over 500,000 tests on samples of water that we routinely collect from our treatment works, reservoirs and randomly selected customer",
UserWaterLook: "Tap water in the UK is amongst the safest and highest quality in the world. Water UK have produced the guide below to help you make the most of your water and answer some questions you may have. You will find a range of advice from how to clean your taps to tips for looking after water storage tanks. Read Water UK's consumer guide",
WaterFilters: "There are several different kinds of home water filters and jug filters available on the market, but each type is designed to remove various compounds from tap water. There is no reason to use these filters on health grounds, as tap water from the mains is high quality and closely monitored. Water that has passed through a domestic filter should be treated as a perishable foodstuff, consumed within 24 hours, and kept in refrigerated conditions. The manufacturer's instructions for the filter equipment should be followed at all times. Visit the British Water website for advice on the installation of filters, softeners and other devices fitted to the water supply in your home.",
Hardness: "Hardness is determined by the level of naturally occurring calcium and magnesium compounds in your water. High content classifies your water as hard, and low traces of the compounds make your water soft. "
};



